### PR TITLE
Migrate pycalphad refdata to ESPEI

### PR DESCRIPTION
**Pull request by bocklund**
Tracking from https://github.com/pycalphad/pycalphad/issues/120

Assume that SGTE91Stable is correct per https://github.com/pycalphad/pycalphad/issues/120. Then we must 

- [x] Remove the metastable phases not present in the SGTE91 original paper
- [ ] Check that remaining phases have correct descriptions

### CODE REVIEW

**Comment by richardotis** [comment]
There are certain metastable phases which are crystallographically equivalent in the unary case, e.g., FCC_A1 and LAVES_C15, meaning it is thermodynamically correct for their lattice stabilities to be the same for pure elements. Some of the entries in `SGTE91` appear to have applied this principle even though it is not used in the original publication. Should we
- Retain these entries (and check for errors),
- Remove these entries, but push this idea further up the stack into ESPEI somewhere as a configuration option, or
- Remove these entries and leave it to the user to apply manually

**Comment by bocklund** [comment]
Looks like some of the stuff removed is actually in SGTE unary 2001 version 4.4, but it doesn't exactly match (e.g. no Laves phases in 2001 v4.4, but there is a comment that Laves was removed)

**Comment by bocklund** [comment]
I think we should not retain the crystallographically similar cases that are degenerate to the SER, as in the Mg and Cu Laves examples. There's value in exactly reproducing the paper. If there were a case where the phase is degenerate with a metastable phase, then it might be worth keeping, but in an ordered dict that's explicitly a modified SGTE91.

**Comment by bocklund** [comment]
For now, I think I am going to set this effort of checking for correctness aside and just focus on fixing the Cu-Mg example and migrating. It's too much work right now to both migrate and prune

**Pull request merged**
