### PR TITLE
Add initial/mean point to chains to fix #243

### LINKED ISSUE #243: MCMC Initialized chains should include initial point
During the initialization of the chains for the MCMC optimizer, a Gaussian distribution about an initial point is taken.
https://github.com/PhasesResearchLab/ESPEI/blob/7c797191d4c3178fe4a22275bbaee9c2977786ad/espei/optimizers/opt_mcmc.py#L98

I would suggest including the initial point in that set of initial chains. If everything is set up correctly, this won't matter, but for cases where the standard deviation is too high while the initial guess is quite good, the current behavior will lead to a lot of bad starting points. Modifying the initial set to include the initial guess point should ensure that at least this state (or acceptable permutations of it) will survive the MCMC run. What do you think?

### PR DESCRIPTION
**Pull request by toastedcrumpets**
I've attempted to patch issue #243. Running pytest before/after the patch I get the same number of errors, i.e. 

```
collected 300 items

espei/analysis.py .                                                                                              [  0%]
espei/datasets.py .                                                                                              [  0%]
espei/espei_script.py .                                                                                          [  1%]
espei/plot.py ssss                                                                                               [  2%]
espei/priors.py ....                                                                                             [  3%]
espei/sublattice_tools.py ..                                                                                     [  4%]
espei/utils.py ....                                                                                              [  5%]
espei/parameter_selection/model_building.py .                                                                    [  6%]
espei/parameter_selection/redlich_kister.py .                                                                    [  6%]
tests/test_core_utils.py .....                                                                                   [  8%]
tests/test_database_utils.py ................................................................................... [ 35%]
................................................................................                                 [ 62%]
tests/test_datasets.py ............x.                                                                            [ 67%]
tests/test_error_functions.py ...............................                                                    [ 77%]
tests/test_mcmc.py ...xx....                                                                                     [ 80%]
tests/test_model_building.py ..........                                                                          [ 83%]
tests/test_optimizer.py .                                                                                        [ 84%]
tests/test_parameter_generation.py ....................                                                          [ 90%]
tests/test_parameter_generation_utils.py ....                                                                    [ 92%]
tests/test_plotting.py ....                                                                                      [ 93%]
tests/test_schema.py ..........                                                                                  [ 96%]
tests/test_utils.py ..........                                                                                   [100%]
```
Happy to have comments/reviews!

### CODE REVIEW

**Comment by bocklund** [comment]
@toastedcrumpets Thanks for putting something together! It looks like there's just one failure introduced where we test that the parameter initialization is consistent and not changing. Since this code explicitly changes the parameter initialization, can you please update that test? 

Otherwise looks great :)

**Review by bocklund — CHANGES_REQUESTED** [review]
Here's a link to the function that needs to be updated: https://github.com/PhasesResearchLab/ESPEI/blob/95b09736643397e5d9a23503a8d3a0ff7ba42ef6/tests/test_mcmc.py#L127

**Comment by toastedcrumpets** [comment]
Apologies @bocklund, I didn't see that test failure for some reason, but sure enough its there when I rerun pytest now. I've patched this if you want to try rerunning the checks?

**Review by bocklund — APPROVED** [review]
Thanks, looks great! :)

**Pull request merged**
